# Generated by Django 3.1.2 on 2020-10-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_size', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TruckDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.TextField(max_length=50)),
                ('container_number', models.TextField(max_length=50)),
                ('freight', models.FloatField(default=0)),
                ('overload', models.FloatField(default=0)),
                ('liftoff', models.FloatField(default=0)),
                ('advanced', models.FloatField(default=0)),
                ('diesel', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('city_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C', to='api.citydetail')),
                ('city_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='D', to='api.citydetail')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='F', to='api.customercompanydetail')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='H', to='api.ordertype')),
                ('package_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='E', to='api.packagedetail')),
                ('truck_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='A', to='api.truckdetail')),
            ],
        ),
    ]
