# Generated by Django 3.1.2 on 2020-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_billdetail_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.TextField(max_length=50000)),
            ],
        ),
        migrations.AddField(
            model_name='billdetail',
            name='dummy_model',
            field=models.ManyToManyField(to='api.DummyModel'),
        ),
    ]
