# Generated by Django 3.1.2 on 2020-10-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201015_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetail',
            name='dummy_model',
        ),
    ]
