# Generated by Django 3.1.2 on 2020-10-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_billdetail_dummy_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='container_number',
            field=models.TextField(default='NILL', max_length=50),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='lr_number',
            field=models.TextField(default='NILL', max_length=50),
        ),
    ]
