# Generated by Django 3.1.2 on 2020-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201017_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='container_number',
            field=models.TextField(blank=True, default='NILL', max_length=50),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='lr_number',
            field=models.TextField(blank=True, default='NILL', max_length=50),
        ),
    ]
