# Generated by Django 3.1.2 on 2020-10-17 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201017_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
