# Generated by Django 3.1.2 on 2020-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_billdetail_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='tds',
            field=models.FloatField(default=0),
        ),
    ]
